### PR TITLE
Fix issue #42

### LINKED ISSUE #42: erc20 module transfer_from() may fail *after* writing to state
In current Substrate, it is the responsibility of the runtime module not to modify chainstate *and* return an Err. Module functions can do one of the above, but not both.

The transfer_from() modifies chain state, then calls _transfer() which may fail if sender balance is not enough.

### PR DESCRIPTION
**Pull request by temp-lovesh**
During `transfer_from`, update allowance once transfer is successful
Signed-off-by: lovesh <lovesh.bond@gmail.com>

### CODE REVIEW

File: modules/erc20/src/erc20.rs [hunk 1]
```diff
@@ -83,19 +83,35 @@ decl_module! {
...
             ensure!(<Allowance<T>>::exists((token_id, from.clone(), to.clone())), "Allowance does not exist.");
             let allowance = Self::allowance((token_id, from.clone(), to.clone()));
+
             ensure!(allowance >= value, "Not enough allowance.");
 
+            // Following code checks if `to` is allowed to get `value` amount of tokens, if it is
+            // then transfer the tokens and decrease `to`'s allowance. An cleaner alternate
+            // would have been to have a separate function `has_sufficient_balance` that checks if
+            // `from` has sufficient tokens so that both checks, for allowance and sufficient balance can
+            // be done before doing any write
```
Comment (bddap) [inline modules/erc20/src/erc20.rs]: Agreed.

**Review by bddap — APPROVED** [review]
This fixes the problem. Looks good.

**Review by bddap — APPROVED** [review]
This fixes the problem. Looks good.
